version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
platform: x64
before_build:
- gradlew.bat spotlessApply
build_script:
- gradlew.bat build
artifacts:
- path: releases\release-*\bundles\tokentool-*.exe
  name: TokenTool-Install
- path: releases\release-*\tokentool-*.jar
  name: TokenTool-Jar
deploy_script:
- gradlew.bat deploy
- dir Deployments
deploy:
- provider: GitHub
  description: Windows release from AppVeyor
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: J2mFPaAOI3z2AOUG28I1mFzTB5eIJ7cyAJpEBHRtRA3s2Zz54IUzKt+MuT3ufw6D
  artifact: TokenTool-Install, TokenTool-Jar
  draft: true
  prerelease: false
  force_update: false
  on:
    appveyor_repo_tag: true
notifications:
- provider: Webhook
  url: https://discordapp.com/api/webhooks/399650806032367616/7biqTSlqVIGCAsqZR1vzq8neErZ2kzmDZ5Y4llL0WFwST073vC24_Btqm6uePNU1DWOC
  method: GET
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
