language: java
sudo: false
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode8.3
install: true
addons:
  apt:
    packages:
    - oracle-java8-installer
    - fakeroot
script: 
  - ./gradlew build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
  - ./gradlew deploy
deploy:
  provider: releases
  api_key:
    secure: hTBFlftPw61rqEx5+4z+VUHxDWi6l9wcIKQFipLnVHlLeQ1neW1pZ8y7WBvXUWCtZ3/D0iTVJpMlWtpWnu6OoMDbFRAOfy2/2kU7bGUDGoH0QGGwrXjAGhs7GY3s+6eu1/uRWUsZ3Ys/vrBrJxyADGThdhD0QxwQ7SuuwM0ERvD94JuyjfvCFZ6xvOjccYdzilmxC4cRvOrBqv1PHTOLkPoQcXsP/FqUdzUAXrud5iUFw8+4el6kLZT/vmbIE8EdpocAKca8QOjf1AMWCPnr5JwKU+n2PUpEqI1WtFA9PatjR2M1e0yvQFWT0mb/rcfZ6LJEPb/s6cFlHCa0aosgV+aj6tN6K81zLj65L+Vv6F4dJNqW40wkBXRfcen0SR4duLlKx5jSHm3XA6Q5b9aI8+XL12cmFZoKYG+yuVgCYAx/qxHBs6es/wMaGkNrxataKsfzwm4Dw8QGKu+115bsxEywFhEbQfFYvClP9/WFEgrdBdP2bplLpFSGDgv2n6DmJq083CV7bJmxgoqhAhjCry/UL9DG0WFtE1FqWsoxzAUoklDxAE0zgW9D66Xucp5dthuVJbzMpxUiR5zRf8npz/NaRAH7EK1ROl9ue67mtuUobMN7+lnG3pszyxTT/y7kqy0OWFvaGnXJ4UMPbBnXXYdFKc+rSO86/4aWWVE3lwQ=
  file_glob: true
  file: releases/release-*/bundles/*
  overwrite: true
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  draft: true
  on:
    repo: RPTools/tokentool
    tags: true
    all_branches: true
